/*
Enter your query here.
Please append a semicolon ";" at the end of the query
*/

SELECT DISTINCT PROFESSOR.NAME, COURSE.NAME FROM SCHEDULE 
LEFT JOIN PROFESSOR on SCHEDULE.PROFESSOR_ID = PROFESSOR.ID 
LEFT JOIN COURSE on SCHEDULE.COURSE_ID = COURSE.ID
WHERE PROFESSOR.DEPARTMENT_ID != COURSE.DEPARTMENT_ID;

